# NumPy Exercises — Beginner Set

20 exercises covering array creation, indexing, math, and manipulation. Each cell is self-contained.

In [2]:
import numpy as np

## 1. Array from 10 to 50

In [3]:
arr = np.arange(10, 51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


## 2. 3x4 Zeros with Last Column Set to 1

In [4]:
arr = np.zeros((3, 4))
arr[:, -1] = 1
print(arr)

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


## 3. 5 Random Integers Between 1 and 100

In [5]:
arr = np.random.randint(1, 101, 5)
print(arr)

[61 16 10 66 32]


## 4. 4x4 Identity Matrix

In [6]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 5. Even Numbers from 2 to 100

In [7]:
arr = np.arange(2, 101, 2)
print(arr)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


## 6. Replace Elements Greater Than 50 with 0

In [8]:
arr = np.array([78, 40, 88, 4, 6, 8, 9, 95, 23, 55])
arr[arr > 50] = 0
print(arr)

[ 0 40  0  4  6  8  9  0 23  0]


## 7. Reshape a matrix

In [9]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 8. Access Element from 3D Array

In [10]:
arr = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4]],
    [[9, 10, 11, 12], [13, 14, 15, 16], [5, 6, 7, 8]],
    [[17, 18, 19, 20], [21, 22, 23, 24], [9, 0, 1, 2]]
])
print("arr[1][2]:", arr[1][2])

arr[1][2]: [5 6 7 8]


## 9. Reverse a 1D Array

In [11]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[::-1])

[5 4 3 2 1]


## 10. Split 1D Array into 5 Equal Parts

In [12]:
arr = np.arange(1, 11)
parts = np.split(arr, 5)
for part in parts:
    print(part)

[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]


## 11. Sum, Mean, Std, Variance

In [13]:
arr = np.array([1, 2, 3, 4, 5])
print("sum:", arr.sum())
print("mean:", arr.mean())
print("std:", arr.std())
print("var:", arr.var())

sum: 15
mean: 3.0
std: 1.4142135623730951
var: 2.0


## 12. Dot Product of Two Arrays

In [14]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
print("dot product:", np.dot(a, b))

dot product: 130


## 13. Normalize Array Between 0 and 1

In [15]:
arr = np.array([1, 2, 3, 4, 5])
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


## 14. Count Zeros, Positives, and Negatives

In [16]:
arr = np.array([1, 2, 3, 0, 6, 4, -3, -4, 0, -9, 0, -7, 0])
print("zeros:", np.sum(arr == 0))
print("positives:", np.sum(arr > 0))
print("negatives:", np.sum(arr < 0))

zeros: 4
positives: 5
negatives: 4


## 15. Replace Odd Numbers with -1

In [17]:
arr = np.array([2, 1, 4, 6, 7, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 2 -1  4  6 -1 -1]


## 16. Transpose Using swapaxes

In [18]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
print("original shape:", arr.shape)
swapped = np.swapaxes(arr, 0, 1)
print("transposed shape:", swapped.shape)
print(swapped)

original shape: (3, 4)
transposed shape: (4, 3)
[[ 10  50  90]
 [ 20  60 100]
 [ 30  70 110]
 [ 40  80 120]]


## 17. Random Matrix

In [19]:
arr = np.random.randint(1, 100, (8, 8))
print(arr)

[[67 20  9 97 28 74  5 68]
 [56  2 14 89 86 17 45 54]
 [ 5  2 91 26 32 88 20 75]
 [79 74 86 90 90 30 75 76]
 [22 84 76 43 42 49  3 14]
 [35 81 42 38 45 26 57 21]
 [95 98 12 13 15 46  6 78]
 [60 81  5 44 67 32 36 38]]


## 18. Element wise multiplication

In [20]:
rows = np.arange(5).reshape(5, 1)
cols = np.arange(5).reshape(1, 5)
result = rows * cols
print(result)

[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]


## 19. Remove Duplicate Rows

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9], [4, 5, 6]])
unique_rows = np.unique(arr, axis=0)
print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 20. Cumulative Sum

In [22]:
arr = np.array([1, 2, 3, 4, 5])
print(np.cumsum(arr))

[ 1  3  6 10 15]


## 21. Row with Maximum Sum

In [23]:
arr = np.array([[3, 6], [6, 0], [6, 5]])
row_sums = np.sum(arr, axis=1)
print("row sums:", row_sums)
print("max row sum:", row_sums.max())
print("row index:", row_sums.argmax())

row sums: [ 9  6 11]
max row sum: 11
row index: 2
